apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-hs-mern-himani
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-hs-mern-himani
  template:
    metadata:
      labels:
        app: frontend-hs-mern-himani
    spec:
      containers:
      - name: frontend-microservice
        image: us-central1-docker.pkg.dev/graphic-parsec-413206/frontend/frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: RREACT_APP_API_HELLO
            value: "http://34.136.112.175/"
          - name: REACT_APP_API_URL
            value: "http://34.42.47.106/fetchuser"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-be-service
spec:
  selector:
    app: frontend-hs-mern-himani
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer